Cu 2nq50qa
freedom-rains/rains pull request #101
Opened 2022-08-11 18:17 UTC by RealDavidH

Client:
-Added Login test component that is just a test component to test routes from front end. 

Server:

In main index.js;
- added cors options to allow api calls from localhost:3001, and staging.freedom.rains.com

In Utils Folder:
-Moved validations to their own file (validations.js)
-in jwt.js update to check for token in the browser storage. 

in validations.js
- Added a new validation method for logging in.

in index.js
- Removed all validation methods and moved them
- added "authenticateToken" method
- ^ Gets token from cookie and makes sure it's valid

in Controllers Folder:
- in userController updated login user to send a jwt token to the browers cookies
- in userController updated all routes that need a jwt token to call from the right req object

In Routes Folder:
- in userRoutes, added authenticate token route to all the routes that require it.

2022-08-11 18:17 UTC, freedom-rains commented
Task linked: [CU-2nq50qa More Efficient JWT](https://app.clickup.com/t/2nq50qa)

2022-08-12 03:16 UTC, taholland submitted a review, later dismissed

2022-08-12 03:16 UTC, taholland commented on server/package.json
> +    "bcrypt": "^5.0.1",
`"bcrypt": "^5.0.1"` needs to be removed. It throws an error in lamdba api gateway for the api.
`"bcryptjs": "^2.4.3",` is being used to replace it. It does the same functionality, but doesn't cause an error in lamdba api gateway.

2022-08-12 03:16 UTC, taholland commented on server/routes/userRoutes/user.route.js
> +  // app.get('/users/:id', userController.getOneUserId); // gets 1 user. Requires (ID) outdated??
we can remove this if `/user` is the new endpoint call now

2022-08-12 03:16 UTC, taholland commented on client/src/requests/client-request.js
> +    method: 'POST',
should be back `method: body ? 'POST' : 'GET',` otherwise every endpoint is going to be a POST method

2022-08-12 03:16 UTC, taholland commented on server/controllers/userControllers/user.controller.js
> +module.exports.getOneUserId = (req, res) => { //This might be outdated
Can remove this function since its outdated

2022-08-12 03:16 UTC, taholland commented on server/routes/userRoutes/user.route.js
> +  // app.get('/users/:id', getOneUserId); // gets 1 user. Requires (ID) outdated??
remove this if it's outdated

2022-08-12 03:16 UTC, taholland commented on server/utils/__tests__/index.js
>  const md5 = require('md5');
you should be able to remove all instances of md5

2022-08-12 03:16 UTC, taholland commented on server/utils/index.js
> +const md5 = require('md5'); // this might be un needed
you should be able to remove all instances of md5

2022-08-12 03:16 UTC, taholland commented on server/package.json
>      "md5": "^2.3.0",
you should be able to remove all instances of md5

2022-08-12 16:48 UTC, drewlacob commented on server/utils/index.js
> +  console.log(token);
remove console log

2022-08-12 16:51 UTC, drewlacob approved these changes

2022-08-12 16:51 UTC, drewlacob commented
Looks good to me other than changes already requested

2022-08-12 16:55 UTC, RealDavidH commented on client/src/requests/client-request.js
> +    method: 'POST',
Yep that was my mistake. I forgot to change it back. I was fiddling with it for testing.

2022-08-12 17:22 UTC, drewlacob commented on server/utils/validations.js
> +
extra empty line

2022-08-12 17:46 UTC, freedom-rains requested changes

2022-08-12 17:46 UTC, freedom-rains commented on server/utils/__tests__/index.js
> +// const { secret } = require('../../config');
You can remove this line if it’s not being used

2022-08-12 17:46 UTC, freedom-rains commented on server/routes/userRoutes/user.route.js
> -const {getAllUser, getOneUserId, loginUser, addUser, updateUser, deleteUser, forgotPassword} = require('./../../controllers/userControllers/user.controller');
Use destructing instead of a single variable

2022-08-12 17:46 UTC, freedom-rains commented on server/routes/userRoutes/user.route.js
> -  app.delete('/users/delete/:id', deleteUser); // deletes a user. Requires (ID)
Bring back the forgot password endpoint

2022-08-12 17:46 UTC, freedom-rains commented on server/routes/userRoutes/user.route.js
> +  app.get('/users', userController.getAllUser); // gets all users. Requires no params
Remove `userController.` you will only need the name of the function using destructing

2022-08-12 18:15 UTC, freedom-rains commented on server/utils/validations.js
> +
@RealDavidH i think this is the only thing left in your PR that’s stopping it from being fully approved

2022-08-12 18:25 UTC, freedom-rains approved these changes

2022-08-12 20:01 UTC, merged