FEAT: Sends new leads to freedomrains CU-3r2m44p
freedom-rains/rains pull request #108
Opened 2022-08-15 18:10 UTC by mclaurind

* addLeads endpoint notifies info@freedomrains.com about new leads

2022-08-15 18:10 UTC, freedom-rains commented
Task linked: [CU-3r2m44p BE - Add lead sends email](https://app.clickup.com/t/3r2m44p)

2022-08-15 18:26 UTC, RealDavidH requested changes

2022-08-15 18:26 UTC, RealDavidH commented on server/controllers/leadsControllers/leads.controller.js
> +      message: 'Your zip code is not the correct length',
doesn't validate input already return a message?

2022-08-15 18:26 UTC, RealDavidH commented on server/controllers/leadsControllers/leads.controller.js
> +  if (validateInput({ zip: zip }).length) {
Why two if's for validate input? doesn't the validation take in an object? like vaildateInput(userInfo.body)

2022-08-15 18:26 UTC, RealDavidH commented on server/controllers/leadsControllers/leads.controller.js
> +  const sent = await sendEmail(email, 'info@freedomrains.com', subject, text);
Add a .catch, and a .then instead of if's and else's below this. it won't change anything, but it's just to keep everything uniform in every file

2022-08-15 18:26 UTC, RealDavidH commented on server/controllers/leadsControllers/leads.controller.js
> +};
extra?

2022-08-15 18:31 UTC, mclaurind commented on server/controllers/leadsControllers/leads.controller.js
> +  if (validateInput({ zip: zip }).length) {
code formatter was just editing the line

2022-08-15 18:31 UTC, mclaurind commented on server/controllers/leadsControllers/leads.controller.js
> +};
code formatter was just editing the line

2022-08-15 18:32 UTC, mclaurind commented on server/controllers/leadsControllers/leads.controller.js
> +      message: 'Your zip code is not the correct length',
code formatter was just editing the line

2022-08-16 12:19 UTC, freedom-rains approved these changes

2022-08-18 12:04 UTC, merged