CHORE: Shop page rework
freedom-rains/rains pull request #90
Opened 2022-08-04 17:35 UTC by MasonBoom

- Added product and shipping details sections to the product class page
- fixed platform tag functionality
- Added arrows and secondary images for when there is more than one image for any given product

2022-08-04 18:39 UTC, freedom-rains requested changes

2022-08-04 18:39 UTC, freedom-rains commented on server/utils/jwt.js
> +  return expressjwt({ secret, algorithms: ['HS256'] }).unless({
This shouldn’t be changed. I would revert this back to what the develop branch has

2022-08-04 18:39 UTC, freedom-rains commented on client/src/pages/product-class/index.js
> +import RightArrow from '../../assets/icons/rightArrow.svg';
RightArrow should actually look like this `rightArrow` Since it’s not a component. Only components should have the first letter capitalized

2022-08-04 18:39 UTC, freedom-rains commented on client/src/pages/product-class/index.js
> +  console.log(prodItem.product.metadata);
Remove your console log

2022-08-08 19:19 UTC, freedom-rains approved these changes

2022-08-09 17:18 UTC, vvyn approved these changes

2022-08-10 10:36 UTC, merged