CHORE: Customer-Service Page CU-2kwfh29
freedom-rains/rains pull request #91
Opened 2022-08-04 17:51 UTC by madivallarino

-The Accordion animation style is wrong and I can't figure out how to do it in the way the design mock ups show without using routes 

-& its missing the navbar but I assumed that would be a global fix so I didn't need to bother with it

2022-08-04 17:51 UTC, freedom-rains commented
Task linked: [CU-2kwfh29 Create Customer Service Page](https://app.clickup.com/t/2kwfh29)

2022-08-04 21:58 UTC, taholland requested changes

2022-08-04 21:58 UTC, taholland commented on client/src/pages/customer-service/index.js
> +      <FormContainer>
instead of using this form you created. Lets just use ContactUs component. Less work and we just use what we've already created

2022-08-05 16:14 UTC, vvyn commented on client/src/page-view.js
> +        <Route exact path="/customer-service">
can you change "/customer-service" to "/faqs"

2022-08-05 16:18 UTC, vvyn commented on client/src/pages/customer-service/index.js
> +
remove empty line

2022-08-05 16:19 UTC, vvyn commented on client/src/pages/customer-service/customer-service.style.js
> +
you may want to clean up some of the spacing on this page

2022-08-05 17:45 UTC, vvyn approved these changes

2022-08-05 17:47 UTC, freedom-rains approved these changes
@madivallarino you are all good. Just need to resolve your merge conflicts before merging into the develop branch

2022-08-08 19:03 UTC, merged