FEAT: Forgot Password Endpoint CU-2rjdgbd
freedom-rains/rains pull request #96
Opened 2022-08-08 15:04 UTC by drewlacob

- add forgot password endpoint which creates a temporary password, sets it in the db, and emails it to the given email
- setup nodemailer and create mailer util to handle mail requests
- set up SiB accounts, hooked in through .env.local and then config
- update api

2022-08-08 15:04 UTC, freedom-rains commented
Task linked: [CU-2rjdgbd BE - Forgot Password endpoint ](https://app.clickup.com/t/2rjdgbd)

2022-08-08 18:41 UTC, RealDavidH reviewed
How do we only give the temp password to the user who needs it? What if I put in your email and get a temp password for your account?

2022-08-08 19:05 UTC, freedom-rains requested changes

2022-08-08 19:05 UTC, freedom-rains commented on server/utils/mailer.js
> +      from: 'freedomtvplus@gmail.com',
Change to be `info@freedomrains.com`

2022-08-08 19:08 UTC, freedom-rains commented
> How do we only give the temp password to the user who needs it? What if I put in your email and get a temp password for your account?

@RealDavidH say I type in your email address in the “Forgot Password” section of the website. Even if you weren’t the one to do it, you will still get the email letting you know your password has been temporarily reset. Then you would just have to use the temporary password to login and then change you password. I (as the person who typed in your email) should never get the email that has your new temporary password.

2022-08-09 13:05 UTC, freedom-rains approved these changes

2022-08-09 13:43 UTC, AlamTahmidul commented
Shouldn't we return the response status codes instead of ending them to make sure that at least something gets sent back to the client?

2022-08-09 18:32 UTC, mclaurind approved these changes

2022-08-10 16:14 UTC, drewlacob commented
> Shouldn't we return the response status codes instead of ending them to make sure that at least something gets sent back to the client?

Can you mark the lines that you are talking about? Do you mean in the mailer util? In the user controller it handles if it was sent or not and returns a status based on that.

2022-08-10 16:26 UTC, merged